apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-nodeport-svc
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
